

import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Nav from '../../components/Nav';
import Footer from '../../components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Lorenzo Washington Portfolio',
  description: 'Generated by next + sanity',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className='h-max'>
      
      <body className='max-w-4xl mx-auto pt-10 h-full block'>
        <Nav/>
        <hr className='hidden'/>
        <main className='pb-20 pt-12 h-fit flex flex-col justify-center' >
          {children}
          
          
        </main>
        
      </body>
      <hr/>
      <div className='bottom-0 h-fit'>
            <Footer/>
      </div>
    </html>
  )
}
